name: Greeting from Resul Mamiyev
on: push

jobs:
  my-jobs:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My Name is
        FIRST_NAME: Resul
        LAST_NAME: Mamiyev
      run: |
        echo $MY_VAR $FIRST_NAME $LAST_NAME.
